### ISSUE TITLE
Failed to activate the restore-windows package

### ISSUE THREAD

**Issue by roelofr** [norio-nomura/restore-windows#5]
This happens after the app is updated, could be fixed by now though. I haven't seen the error on my Windows desktop but that updates more often (nightly).

Enter steps to reproduce below:

1. Update the app (in my scenario, from 0.3.5 to 0.4.1)
2. Error

**Atom Version**: 0.188.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [restore-windows](https://github.com/norio-nomura/restore-windows) package, v0.4.1

### Stack Trace

Failed to activate the restore-windows package

```
At EPERM, operation not permitted 'C:\Users\Roelof\.atom\restore-windows\opened\50d08c98edc295401e46c77053955b0d'

Error: EPERM, operation not permitted 'C:\Users\Roelof\.atom\restore-windows\opened\50d08c98edc295401e46c77053955b0d'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.exports.addToOpened (C:\Users\Roelof\.atom\packages\restore-windows\lib\restore-windows.coffee:58:19)
  at Object.module.exports.projectPathChanged (C:\Users\Roelof\.atom\packages\restore-windows\lib\restore-windows.coffee:33:5)
  at Object.module.exports.activate (C:\Users\Roelof\.atom\packages\restore-windows\lib\restore-windows.coffee:20:45)
  at Package.module.exports.Package.activateNow (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:240:19)
  at C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:461:21)
  at C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:226:29
  at exit (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Roelof\AppData\Local\atom\app-0.188.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
  3x -6:09.1 core:paste (atom-text-editor.editor)
     -6:05.5 core:move-down (atom-text-editor.editor)
     -6:05.3 editor:move-to-beginning-of-word (atom-text-editor.editor)
     -6:05.1 editor:select-to-end-of-word (atom-text-editor.editor)
  2x -6:04.0 core:backspace (atom-text-editor.editor)
     -6:03.4 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -6:03.1 core:select-down (atom-text-editor.editor)
     -6:02.8 editor:select-to-end-of-line (atom-text-editor.editor)
     -6:02.5 core:backspace (atom-text-editor.editor)
     -6:02.3 core:save (atom-text-editor.editor)
     -1:05.7 core:copy (atom-text-editor.editor)
     -1:03.0 core:paste (atom-text-editor.editor)
     -0:54.4 core:copy (atom-text-editor.editor)
  3x -0:53.4 core:paste (atom-text-editor.editor)
  2x -0:47.8 core:save (atom-text-editor.editor)
     -0:38.6 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics",
      "minimap-git-diff"
    ],
    "autoHideMenuBar": true,
    "projectHome": "D:\\Users\\Roelof\\Documents\\Development"
  }
}
```

### Installed Packages

```coffee
# User
css-snippets, v0.5.0
file-type-icons, v0.5.4
js-refactor, v0.3.0
jslint, v1.2.1
language-gmod-lua, v0.3.0
language-javascript-better, v1.2.0
language-javascript-semantic, v0.1.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-lua, v0.1.5
refactor, v0.4.1
remote-sync, v2.4.1
restore-windows, v0.4.1
sass-autocompile, v0.4.0
sync-settings, v0.2.2
time-status, v1.0.1
you-complete-me, v0.1.1

# Dev
No dev packages
```

**Comment by norio-nomura** [comment]
@roelofr Thank you for reporting issue.
This issue is caused by a bug of older version. The bug has been fixed on v0.4.0.

**Comment by NicApicella** [comment]
@norio-nomura I'm surprised this issue is closed; I'm still getting it. :-(
1. Open a couple of Atom windows
2. Within those windows, open a couple of documents each
3. Close Atom
4. Open Atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [restore-windows](https://github.com/norio-nomura/restore-windows) package, v0.4.1

### Stack Trace

Failed to activate the restore-windows package

```
At ENOENT: no such file or directory, unlink '/Users/nicapicella/.atom/restore-windows/mayBeRestored/3c4899c7f9ba966120555f3c1c27204e'

Error: ENOENT: no such file or directory, unlink '/Users/nicapicella/.atom/restore-windows/mayBeRestored/3c4899c7f9ba966120555f3c1c27204e'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:947:18)
    at /Users/nicapicella/.atom/packages/restore-windows/lib/restore-windows.coffee:76:37
    at Array.forEach (native)
    at Object.module.exports.getPathsToReopen (/Users/nicapicella/.atom/packages/restore-windows/lib/restore-windows.coffee:76:19)
    at Object.module.exports.restoreWindows (/Users/nicapicella/.atom/packages/restore-windows/lib/restore-windows.coffee:60:24)
    at Object.module.exports.activate (/Users/nicapicella/.atom/packages/restore-windows/lib/restore-windows.coffee:22:6)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
```

### Commands

```
```

### Config

``` json
{
  "core": {},
  "restore-windows": {}
}
```

### Installed Packages

``` coffee
# User
language-latex, v0.6.1
latexer, v0.2.7
linter, v1.11.3
linter-alex, v1.6.0
linter-chktex, v1.2.3
linter-csslint, v1.1.0
linter-markdown, v1.2.1
linter-pep257, v0.3.1
linter-pep8, v1.0.1
linter-pylint, v1.0.5
linter-tidy, v1.0.1
linter-write-good, v0.6.1
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.2.2
markdown-scroll-sync, v2.0.3
minimap, v4.16.2
restore-windows, v0.4.1

# Dev
No dev packages
```

**Comment by norio-nomura** [comment]
@NicApicella Atom has supported restoring application state since v0.193.0.
http://blog.atom.io/2015/04/21/atom-is-faster-resizable-saves-app-state.html

**Comment by NicApicella** [comment]
@norio-nomura Thanks for the info! Unfortunately, it doesn't seem to work for me. :-( Will be looking for solutions elsewhere. (PS: Can this package be regarded as deprecated then?)

**Comment by norio-nomura** [comment]
@NicApicella Sorry, I have not used this package since Atom v0.193.0.
I don't know whether this package is working with current Atom or not.
Yes, this package is deprecated for me.
If Atom's behavior doesn't satisfy, I think filing an issue to Atom will be better.
